name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.19.0"
          package-manager-cache: false
      - name: Install dependencies
        run: |
          uv sync --dev
          uv pip sync --require-hashes ./requirements.txt --target ./bundled/libs
          npm ci --ignore-scripts
      - name: Run checks
        run: npm run check
      - name: Run tests
        run: uv run --dev python -m unittest

  # ts-tests:
  #   name: TypeScript Tests
  #   runs-on: ubuntu-latest
  #   env:
  #     UV_SYSTEM_PYTHON: 1
  #   steps:
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.8"
  #     - uses: hynek/setup-cached-uv@v1
  #     - uses: actions/checkout@v4
  #     - name: Install dependencies
  #       run: |
  #         uv pip sync --require-hashes ./requirements.txt --target ./bundled/libs
  #         npm ci
  #       shell: bash
  #     - name: Compile tests
  #       run: npm run pretest
  #       shell: bash
  #     - name: Run tests
  #       run: xvfb-run npm run tests
  #       shell: bash
